In [1]:
f = open("results_o.txt", "r")
string = f.read()
f.close()

In [2]:
r = string.split("\n")

In [3]:
rr = [x.split("?") for x in r if '' not in x.split("?")[0:12] ]

In [4]:
import pandas as pd
name_col = rr.pop(0)
df = pd.DataFrame(rr, columns=name_col)
df.head()

In [12]:
df['rtp.p_type']=df['rtp.p_type'].apply(lambda x: x.split(",")[0])

In [13]:
df.head()

0    96
1    20
2    38
3    38
4    96
Name: rtp.p_type, dtype: object

In [5]:
import numpy as np
df = df.astype({'frame.time_epoch': 'float64', 'frame.number' : "int32", 'frame.len' : "int32", \
                'udp.length' : "int32", 'rtp.p_type' : "int32", \
                'rtp.timestamp' : np.int64, "udp.srcport" : "int32", \
                 "udp.dstport" : "int32", 'rtp.marker' : "int32", 'rtp.seq' : "int32", \
           })

df

ValueError: invalid literal for int() with base 10: '99,127,89'

In [26]:
df = df.rename(columns ={
            'frame.time_epoch' : 'timestamps',
            'frame.number' : 'frame_num',
            'frame.len' : "len_frame",
            'ip.src' : 'ip_src',
            'ip.dst' : 'ip_dst',
            'udp.srcport' : 'prt_src',
            'udp.dstport' : 'prt_dst',
            'udp.length' :  'len_udp',
            'rtp.p_type' : 'p_type',
            'rtp.ssrc' : 'ssrc',
            'rtp.timestamp' : 'rtp_timestamp',
            'rtp.seq' : 'rtp_seq_num',
            'rtp.marker' : 'rtp_marker',
             'rtp.csrc.item' : 'rtp_csrc'
                })
df

,timestamps,frame_num,len_frame,ip_src,ip_dst,prt_src,prt_dst,len_udp,p_type,ssrc,rtp_timestamp,rtp_seq_num,rtp_marker,rtp_csrc
0,1.584737e+09,15591,159,192.168.1.94,52.58.251.108,64791,10000,125,111,0x668f2b84,2620562200,15360,1,
1,1.584737e+09,15599,151,52.58.251.108,192.168.1.94,10000,64791,117,111,0xd8656d6d,1747845161,218,0,
2,1.584737e+09,15601,163,192.168.1.94,52.58.251.108,64791,10000,129,111,0x668f2b84,2620563160,15361,0,
3,1.584737e+09,15605,157,192.168.1.94,52.58.251.108,64791,10000,123,111,0x668f2b84,2620564120,15362,0,
4,1.584737e+09,15612,150,52.58.251.108,192.168.1.94,10000,64791,116,111,0xd8656d6d,1747846121,219,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,1.584737e+09,16407,1186,192.168.1.94,52.58.251.108,64791,10000,1152,100,0xb14e07e6,487054115,24624,0,
599,1.584737e+09,16408,1186,192.168.1.94,52.58.251.108,64791,10000,1152,100,0xb14e07e6,487054115,24625,0,
600,1.584737e+09,16409,1187,192.168.1.94,52.58.251.108,64791,10000,1153,100,0xb14e07e6,487054115,24626,1,
601,1.584737e+09,16427,150,192.168.1.94,52.58.251.108,64791,10000,116,111,0x668f2b84,2620617880,15418,0,
602,1.584737e+09,16434,142,192.168.1.94,52.58.251.108,64791,10000,108,111,0x668f2b84,2620618840,15419,0,

In [27]:
df["rtp_csrc"].replace('',"fec", inplace=True)
df

,timestamps,frame_num,len_frame,ip_src,ip_dst,prt_src,prt_dst,len_udp,p_type,ssrc,rtp_timestamp,rtp_seq_num,rtp_marker,rtp_csrc
0,1.584737e+09,15591,159,192.168.1.94,52.58.251.108,64791,10000,125,111,0x668f2b84,2620562200,15360,1,fec
1,1.584737e+09,15599,151,52.58.251.108,192.168.1.94,10000,64791,117,111,0xd8656d6d,1747845161,218,0,fec
2,1.584737e+09,15601,163,192.168.1.94,52.58.251.108,64791,10000,129,111,0x668f2b84,2620563160,15361,0,fec
3,1.584737e+09,15605,157,192.168.1.94,52.58.251.108,64791,10000,123,111,0x668f2b84,2620564120,15362,0,fec
4,1.584737e+09,15612,150,52.58.251.108,192.168.1.94,10000,64791,116,111,0xd8656d6d,1747846121,219,0,fec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,1.584737e+09,16407,1186,192.168.1.94,52.58.251.108,64791,10000,1152,100,0xb14e07e6,487054115,24624,0,fec
599,1.584737e+09,16408,1186,192.168.1.94,52.58.251.108,64791,10000,1152,100,0xb14e07e6,487054115,24625,0,fec
600,1.584737e+09,16409,1187,192.168.1.94,52.58.251.108,64791,10000,1153,100,0xb14e07e6,487054115,24626,1,fec
601,1.584737e+09,16427,150,192.168.1.94,52.58.251.108,64791,10000,116,111,0x668f2b84,2620617880,15418,0,fec
602,1.584737e+09,16434,142,192.168.1.94,52.58.251.108,64791,10000,108,111,0x668f2b84,2620618840,15419,0,fec

In [28]:
columns = ["ssrc", "ip_src", "ip_dst", "prt_src", "prt_dst" , "p_type"]
gb= df.groupby(columns)
dict_flow_data = {x : gb.get_group(x) for x in gb.groups if x is not None and np.max(gb.get_group(x)["timestamps"]) - np.min(gb.get_group(x)["timestamps"])>2}

In [29]:
dict_flow_data

{}

In [32]:
for x in gb.groups:
    print(np.max(gb.get_group(x)["timestamps"]) - np.min(gb.get_group(x)["timestamps"]))

1.0728099346160889
1.1802270412445068
0.5786218643188477
0.7636380195617676
1.003443956375122
1.0677471160888672
1.101417064666748
0.30588316917419434